// Champion Pool Builder's recommendations favor a complementary damage
// type — if your pool leans AD, suggest an AP option too, so losing your
// main to a ban/first-pick still leaves you a real alternative. Data
// Dragon has no damage-type field at all, so this can't be derived from a
// real Riot field the way tags/difficulty are elsewhere in this app.
//
// Unlike everything else in the surrounding codebase, this table is
// hand-classified from game knowledge, not Riot-sourced. It's a real,
// considered classification (checked against each champion's actual kit,
// not guessed from their Data Dragon class tags — those alone are NOT a
// reliable signal, e.g. Zac and DrMundo are Tank/Fighter-tagged but scale
// AP; Diana is Fighter/Assassin-tagged but is a pure AP mage/assassin),
// but it can drift wrong as kits get reworked and should be re-checked
// against patch notes periodically rather than assumed permanent.
//
// "primary" = which damage type actually deals the bulk of the champion's
// output in a normal build, not a literal split. "mixed" is reserved for
// champions whose kit is a genuine, well-known hybrid (both real damage
// sources, not just "can build either") — Kai'Sa, Kayle, Kog'Maw, Corki,
// Varus, Ezreal, Smolder.
//
// A champion whose kit isn't known yet is left `null` rather than guessed
// from its class tags. Kept in sync with the web copy; see that file's
// header for the maintenance policy.
export type DamageType = "AD" | "AP" | "mixed";

export const CHAMPION_DAMAGE_TYPE: Record<string, DamageType | null> = {
  Aatrox: "AD",
  Ahri: "AP",
  Akali: "AP",
  Akshan: "AD",
  Alistar: "AP",
  Ambessa: "AD",
  Amumu: "AP",
  Anivia: "AP",
  Annie: "AP",
  Aphelios: "AD",
  Ashe: "AD",
  AurelionSol: "AP",
  Aurora: "AP",
  Azir: "AP",
  Bard: "AP",
  Belveth: "AD",
  Blitzcrank: "AP",
  Brand: "AP",
  Braum: "AP",
  Briar: "AD",
  Caitlyn: "AD",
  Camille: "AD",
  Cassiopeia: "AP",
  Chogath: "AP",
  Corki: "mixed",
  Darius: "AD",
  Diana: "AP",
  DrMundo: "AP",
  Draven: "AD",
  Ekko: "AP",
  Elise: "AP",
  Evelynn: "AP",
  Ezreal: "mixed",
  Fiddlesticks: "AP",
  Fiora: "AD",
  Fizz: "AP",
  Galio: "AP",
  Gangplank: "AD",
  Garen: "AD",
  Gnar: "AD",
  Gragas: "AP",
  Graves: "AD",
  Gwen: "AP",
  Hecarim: "AD",
  Heimerdinger: "AP",
  Hwei: "AP",
  Illaoi: "AD",
  Irelia: "AD",
  Ivern: "AP",
  Janna: "AP",
  JarvanIV: "AD",
  Jax: "AD",
  Jayce: "AD",
  Jhin: "AD",
  Jinx: "AD",
  KSante: "AD",
  Kaisa: "mixed",
  Kalista: "AD",
  Karma: "AP",
  Karthus: "AP",
  Kassadin: "AP",
  Katarina: "AP",
  Kayle: "mixed",
  Kayn: "AD",
  Kennen: "AP",
  Khazix: "AD",
  Kindred: "AD",
  Kled: "AD",
  KogMaw: "mixed",
  Leblanc: "AP",
  LeeSin: "AD",
  Leona: "AP",
  Lillia: "AP",
  Lissandra: "AP",
  Locke: "AP",
  Lucian: "AD",
  Lulu: "AP",
  Lux: "AP",
  Malphite: "AP",
  Malzahar: "AP",
  Maokai: "AP",
  MasterYi: "AD",
  Mel: "AP",
  Milio: "AP",
  MissFortune: "AD",
  MonkeyKing: "AD",
  Mordekaiser: "AP",
  Morgana: "AP",
  Naafiri: "AD",
  Nami: "AP",
  Nasus: "AD",
  Nautilus: "AP",
  Neeko: "AP",
  Nidalee: "AP",
  Nilah: "AD",
  Nocturne: "AD",
  Nunu: "AP",
  Olaf: "AD",
  Orianna: "AP",
  Ornn: "AP",
  Pantheon: "AD",
  Poppy: "AD",
  Pyke: "AD",
  Qiyana: "AD",
  Quinn: "AD",
  Rakan: "AP",
  Rammus: "AD",
  RekSai: "AD",
  Rell: "AP",
  Renata: "AP",
  Renekton: "AD",
  Rengar: "AD",
  Riven: "AD",
  Rumble: "AP",
  Ryze: "AP",
  Samira: "AD",
  Sejuani: "AD",
  Senna: "AD",
  Seraphine: "AP",
  Sett: "AD",
  Shaco: "AD",
  Shen: "AD",
  Shyvana: "AD",
  Singed: "AP",
  Sion: "AD",
  Sivir: "AD",
  Skarner: "AD",
  Smolder: "mixed",
  Sona: "AP",
  Soraka: "AP",
  Swain: "AP",
  Sylas: "AP",
  Syndra: "AP",
  TahmKench: "AP",
  Taliyah: "AP",
  Talon: "AD",
  Taric: "AP",
  Teemo: "AP",
  Thresh: "AP",
  Tristana: "AD",
  Trundle: "AD",
  Tryndamere: "AD",
  TwistedFate: "AP",
  Twitch: "AD",
  Udyr: "AD",
  Urgot: "AD",
  Varus: "mixed",
  Vayne: "AD",
  Veigar: "AP",
  Velkoz: "AP",
  Vex: "AP",
  Vi: "AD",
  Viego: "AD",
  Viktor: "AP",
  Vladimir: "AP",
  Volibear: "AD",
  Warwick: "AD",
  Xayah: "AD",
  Xerath: "AP",
  XinZhao: "AD",
  Yasuo: "AD",
  Yone: "AD",
  Yorick: "AD",
  Yunara: "AD",
  Yuumi: "AP",
  Zaahen: "AD",
  Zac: "AP",
  Zed: "AD",
  Zeri: "AD",
  Ziggs: "AP",
  Zilean: "AP",
  Zoe: "AP",
  Zyra: "AP",
};

export function damageTypeOf(championInternalId: string): DamageType | null {
  return CHAMPION_DAMAGE_TYPE[championInternalId] ?? null;
}
