// Ported from the web app's src/lib/champion-roles.ts — real habitual
// lane(s) per champion, hand-classified from actual kit knowledge
// (verified via op.gg/mobalytics for the newest and least certain ones)
// rather than derived from Data Dragon's `tags` field, which is a class,
// not a lane, and produced real wrong answers when used as one (Rell
// surfacing for Top through her Tank tag, Naafiri passing a Top filter
// through a secondary tag). Kept in sync with the web copy — see that
// file's own header for the full methodology and maintenance policy.
export type ChampionRole = "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "UTILITY";

export const CHAMPION_ROLES: Record<string, ChampionRole[] | null> = {
  Aatrox: ["TOP"],
  Ahri: ["MIDDLE"],
  Akali: ["MIDDLE", "TOP"],
  Akshan: ["MIDDLE", "TOP"],
  Alistar: ["UTILITY"],
  Ambessa: ["TOP", "JUNGLE"],
  Amumu: ["JUNGLE"],
  Anivia: ["MIDDLE"],
  Annie: ["MIDDLE", "UTILITY"],
  Aphelios: ["BOTTOM"],
  Ashe: ["BOTTOM"],
  AurelionSol: ["MIDDLE"],
  Aurora: ["MIDDLE", "TOP"],
  Azir: ["MIDDLE"],
  Bard: ["UTILITY"],
  Belveth: ["JUNGLE"],
  Blitzcrank: ["UTILITY"],
  Brand: ["UTILITY", "MIDDLE"],
  Braum: ["UTILITY"],
  Briar: ["JUNGLE"],
  Caitlyn: ["BOTTOM"],
  Camille: ["TOP"],
  Cassiopeia: ["MIDDLE"],
  Chogath: ["TOP"],
  Corki: ["MIDDLE"],
  Darius: ["TOP"],
  Diana: ["JUNGLE", "MIDDLE"],
  DrMundo: ["TOP"],
  Draven: ["BOTTOM"],
  Ekko: ["JUNGLE", "MIDDLE"],
  Elise: ["JUNGLE"],
  Evelynn: ["JUNGLE"],
  Ezreal: ["BOTTOM"],
  Fiddlesticks: ["JUNGLE"],
  Fiora: ["TOP"],
  Fizz: ["MIDDLE"],
  Galio: ["MIDDLE", "TOP"],
  Gangplank: ["TOP"],
  Garen: ["TOP"],
  Gnar: ["TOP"],
  Gragas: ["JUNGLE", "TOP"],
  Graves: ["JUNGLE"],
  Gwen: ["TOP", "JUNGLE"],
  Hecarim: ["JUNGLE"],
  Heimerdinger: ["MIDDLE", "TOP"],
  Hwei: ["MIDDLE", "UTILITY"],
  Illaoi: ["TOP"],
  Irelia: ["TOP", "MIDDLE"],
  Ivern: ["JUNGLE"],
  Janna: ["UTILITY"],
  JarvanIV: ["JUNGLE"],
  Jax: ["TOP", "JUNGLE"],
  Jayce: ["TOP", "MIDDLE"],
  Jhin: ["BOTTOM"],
  Jinx: ["BOTTOM"],
  KSante: ["TOP"],
  Kaisa: ["BOTTOM"],
  Kalista: ["BOTTOM"],
  Karma: ["UTILITY", "MIDDLE"],
  Karthus: ["JUNGLE", "MIDDLE"],
  Kassadin: ["MIDDLE"],
  Katarina: ["MIDDLE"],
  Kayle: ["TOP", "MIDDLE"],
  Kayn: ["JUNGLE"],
  Kennen: ["TOP", "MIDDLE"],
  Khazix: ["JUNGLE"],
  Kindred: ["JUNGLE"],
  Kled: ["TOP"],
  KogMaw: ["BOTTOM"],
  Leblanc: ["MIDDLE"],
  LeeSin: ["JUNGLE"],
  Leona: ["UTILITY"],
  Lillia: ["JUNGLE"],
  Lissandra: ["MIDDLE"],
  Locke: ["MIDDLE"],
  Lucian: ["BOTTOM"],
  Lulu: ["UTILITY"],
  Lux: ["MIDDLE", "UTILITY"],
  Malphite: ["TOP"],
  Malzahar: ["MIDDLE"],
  Maokai: ["TOP", "UTILITY"],
  MasterYi: ["JUNGLE"],
  Mel: ["MIDDLE", "UTILITY"],
  Milio: ["UTILITY"],
  MissFortune: ["BOTTOM"],
  MonkeyKing: ["TOP", "JUNGLE"],
  Mordekaiser: ["TOP"],
  Morgana: ["UTILITY", "MIDDLE"],
  Naafiri: ["JUNGLE", "MIDDLE"],
  Nami: ["UTILITY"],
  Nasus: ["TOP"],
  Nautilus: ["UTILITY", "JUNGLE"],
  Neeko: ["MIDDLE", "UTILITY"],
  Nidalee: ["JUNGLE"],
  Nilah: ["BOTTOM"],
  Nocturne: ["JUNGLE"],
  Nunu: ["JUNGLE"],
  Olaf: ["JUNGLE", "TOP"],
  Orianna: ["MIDDLE"],
  Ornn: ["TOP"],
  Pantheon: ["TOP", "UTILITY", "MIDDLE"],
  Poppy: ["TOP", "JUNGLE"],
  Pyke: ["UTILITY"],
  Qiyana: ["MIDDLE", "TOP"],
  Quinn: ["TOP"],
  Rakan: ["UTILITY"],
  Rammus: ["JUNGLE"],
  RekSai: ["JUNGLE"],
  Rell: ["UTILITY"],
  Renata: ["UTILITY"],
  Renekton: ["TOP"],
  Rengar: ["JUNGLE", "TOP"],
  Riven: ["TOP"],
  Rumble: ["TOP", "MIDDLE"],
  Ryze: ["MIDDLE"],
  Samira: ["BOTTOM"],
  Sejuani: ["JUNGLE"],
  Senna: ["UTILITY", "BOTTOM"],
  Seraphine: ["UTILITY", "BOTTOM"],
  Sett: ["TOP", "UTILITY"],
  Shaco: ["JUNGLE"],
  Shen: ["TOP"],
  Shyvana: ["JUNGLE"],
  Singed: ["TOP"],
  Sion: ["TOP"],
  Sivir: ["BOTTOM"],
  Skarner: ["JUNGLE"],
  Smolder: ["BOTTOM"],
  Sona: ["UTILITY"],
  Soraka: ["UTILITY"],
  Swain: ["MIDDLE", "UTILITY"],
  Sylas: ["MIDDLE", "JUNGLE"],
  Syndra: ["MIDDLE"],
  TahmKench: ["UTILITY", "TOP"],
  Taliyah: ["JUNGLE", "MIDDLE"],
  Talon: ["MIDDLE", "JUNGLE"],
  Taric: ["UTILITY"],
  Teemo: ["TOP"],
  Thresh: ["UTILITY"],
  Tristana: ["BOTTOM"],
  Trundle: ["JUNGLE", "TOP"],
  Tryndamere: ["TOP"],
  TwistedFate: ["MIDDLE"],
  Twitch: ["BOTTOM", "JUNGLE"],
  Udyr: ["JUNGLE"],
  Urgot: ["TOP"],
  Varus: ["BOTTOM"],
  Vayne: ["BOTTOM", "TOP"],
  Veigar: ["MIDDLE"],
  Velkoz: ["UTILITY", "MIDDLE"],
  Vex: ["MIDDLE"],
  Vi: ["JUNGLE"],
  Viego: ["JUNGLE"],
  Viktor: ["MIDDLE"],
  Vladimir: ["MIDDLE", "TOP"],
  Volibear: ["TOP", "JUNGLE"],
  Warwick: ["JUNGLE", "TOP"],
  Xayah: ["BOTTOM"],
  Xerath: ["MIDDLE", "UTILITY"],
  XinZhao: ["JUNGLE"],
  Yasuo: ["MIDDLE", "TOP"],
  Yone: ["MIDDLE", "TOP"],
  Yorick: ["TOP"],
  Yunara: ["BOTTOM"],
  Yuumi: ["UTILITY"],
  Zaahen: ["TOP", "JUNGLE"],
  Zac: ["JUNGLE"],
  Zed: ["MIDDLE"],
  Zeri: ["BOTTOM"],
  Ziggs: ["MIDDLE", "BOTTOM"],
  Zilean: ["UTILITY", "MIDDLE"],
  Zoe: ["MIDDLE"],
  Zyra: ["UTILITY", "MIDDLE"],
};

export const ALL_ROLES: ChampionRole[] = ["TOP", "JUNGLE", "MIDDLE", "BOTTOM", "UTILITY"];

export function rolesOf(championInternalId: string): ChampionRole[] | null {
  return CHAMPION_ROLES[championInternalId] ?? null;
}

export function primaryRoleOf(championInternalId: string): ChampionRole | null {
  return CHAMPION_ROLES[championInternalId]?.[0] ?? null;
}
